import React, { useRef, useState, useEffect } from "react";
import { useDispatch } from "react-redux";
import { updateJobAsync } from "../../redux/jobs/thunks";
import Button from '@mui/material/Button';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import '../../styles/Job.css';
import Tags from "../Tags";
import Fab from '@mui/material/Fab';
import AddIcon from '@mui/icons-material/Add';
import Chip from '@mui/material/Chip';

export default function Job({job}) {
    // console.log({job})
    const dispatch = useDispatch();

    const [jobTitle, setJobTitle] = useState('');
    const [company, setCompany] = useState('');
    const [jobType, setJobType] = useState('');
    const [location, setLocation] = useState('');
    const [dateApplied, setDateApplied] = useState('');
    const [duration, setDuration] = useState('');
    const [link, setLink] = useState('');
    const [coverLetter, setCoverLetter] = useState('');
    const [tailoredCoverLetter, setTailoredCoverLetter] = useState('');
    const [tags, setTags] = useState([])
    const [tag, setTag] = useState('')
    const [temptags, setTempTags] = useState([])

    const jobTitleInputRef = useRef();
    const companyInputRef = useRef();
    const jobTypeInputRef = useRef();
    const locationInputRef = useRef();
    const dateAppliedInputRef = useRef();
    const durationInputRef = useRef();
    const linkInputRef = useRef();
    const coverLetterInputRef = useRef();
    const tailoredCoverLetterInputRef = useRef();

    const [anchorEl, setAnchorEl] = React.useState(null);
    const open = Boolean(anchorEl);
    const handleClick = (event) => {
        setAnchorEl(event.currentTarget);
    };
    const handleClose = () => {
        setAnchorEl(null);
    };

    // The following snippet of code for useEffect and value={<some job field value>} in
    // each job-field container was generated by ChatGPT 3.5 on June 20, 2024
    // The prompt was: "why isn't the job details panel on the right changing accordingly 
    // when a different job is selected on the left jobList panel?", including feeding
    // it the code in JobsContainer.jsx, JobList.jsx and the previous code for Job.jsx
    useEffect(() => {
        if (job) {
            console.log('Job data received (Job.jsx):', job);
            setJobTitle(job.jobTitle || '');
            setCompany(job.company || '');
            setJobType(job.jobType || '');
            setLocation(job.location || '');
            setDateApplied(job.dateApplied || '');
            setDuration(job.duration || '');
            setLink(job.link || '');
            setCoverLetter(job.coverLetter || '');
            setTailoredCoverLetter(job.tailoredCoverLetter || '');
            setTags(job.tags || [])
            setTempTags(job.tags || [])
        }
    }, [job])

    // useEffect(() => {
    //     console.log(temp_tags)
    // }, [temp_tags])
 
    // The following useEffect and adjustWidth function was generated by ChatGPT 3.5 on June 20, 2024
    // The promt was: "how do I make it so that the input in Jobs.jsx actually fit to the length of the
    // text contained within it? as you can see, the job title is being cut off", including a screenshot
    // that showed how the text fields were cutt off
    useEffect(() => {
        adjustWidth(jobTitleInputRef.current);
        adjustWidth(companyInputRef.current);
        adjustWidth(jobTypeInputRef.current);
        adjustWidth(locationInputRef.current);
        adjustWidth(dateAppliedInputRef.current);
        adjustWidth(durationInputRef.current);
        adjustWidth(coverLetterInputRef.current);
        adjustWidth(tailoredCoverLetterInputRef.current);
    }, [jobTitle, company, jobType, location, dateApplied, duration, link, coverLetter, tailoredCoverLetter]);

    const adjustWidth = (input) => {
        if (input) {
            input.style.width = `${input.value.length + 1}ch`;
        }
    }

    return(
        <>
        <div className="w-[80%] m-auto h-[70%] overflow-y-scroll border rounded-[35px]">
            <div className="flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Job Title:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Job Title" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Job Title</span></div> </div>
            </div>
            <div className="flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Company:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Company" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Company</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Job Type:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Job Type" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Job type</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Location:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Location" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Location</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Date Applied:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Date Applied" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Date Applied</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Duration:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Duration" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Duration</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Link:
                </div>
                <div className="p-[30px] grow"> <div className=" relative"><input type="text" name="" id="" placeholder="Link" className="border p-2 rounded-[30px]"/> <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Link</span></div> </div>
            </div>
            <div className=" flex border-b">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Tags:
                </div>
                <div className="p-[30px] grow"> 
                    {/* <div className=" relative">
                        <input type="text" name="" id="" placeholder="Enter new Tag" className="border p-2 rounded-[30px]"/> 
                        <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Tags</span>
                    </div> */}

                    <div className="">
                        {/* <input id="tags" 
                                className="auto-width-input"
                                value={tag}
                                onChange={(e) => {
                                    setTag(e.target.value);
                                    adjustWidth(e.target);
                                }}> */}
                        <div className="relative">
                            <input type="text" name="" id="" placeholder="Enter new Tag" value={tag} className="border p-2 rounded-[30px] mr-2 mb-2" onChange={(e) => {
                                    setTag(e.target.value);
                                    // adjustWidth(e.target);
                                }}/> 
                            
                            <span className=" bg-white p-1 text-[11px] absolute left-[14px] top-[-12px]">Tags</span>

                            <Fab size="small" color="primary" aria-label="add" className="add-tag" onClick={() => {if (tag != ''){console.log("pushing"); let new_tags = [...temptags]; new_tags.push(tag); setTempTags([...new_tags]); setTag(''); console.log('updated tags:', temptags)}}}> 
                                <AddIcon />
                            </Fab>
                        </div>
                         
                        {/* <input type="button" className="add-tag" value="+" onClick={() => {if (tag != ''){console.log("pushing"); let new_tags = [...temptags]; new_tags.push(tag); setTempTags([...new_tags]); console.log(temptags)}}}/> */}
                        <div className="flex lex-auto flex-row items-center">
                                {console.log(temptags)}
                                {/* <div className="flex-auto flex-row items-center">*/}
                                {temptags.map((tag, i) => {
                                        console.log(tag);
                                        // return <div className="rounded-md bg-sky-400 w-[100px] flex justify-between p-1"><div className="">{tag}</div> <input type="button" value="X" onClick={() => {let new_tags = [...temptags]; new_tags.splice(i, 1); setTempTags([...new_tags]); console.log(temptags)}}/> </div> 
                                        return <Chip
                                            label={tag}
                                            sx={{
                                                fontFamily: "Montserrat",
                                                marginRight: 0.5
                                            }}
                                            onDelete={() => {let new_tags = [...temptags]; new_tags.splice(i, 1); setTempTags([...new_tags]); console.log(temptags)}} 
                                            />
                                })}
                        </div>
                    </div> 
                </div>
            </div>
            <div className=" flex">
                <div className="font-bold w-[208px] p-[30px] border-r">
                    Cover Letter Used:
                </div>
                <div className="p-[30px] grow rounded-br-[30px]"> 
                    <div>
                            <Button
                                                                        id="basic-button"
                                                                        aria-controls={open ? 'basic-menu' : undefined}
                                                                        aria-haspopup="true"
                                                                        aria-expanded={open ? 'true' : undefined}
                                                                        onClick={handleClick}
                                                                    >
                                                                        Choose Cover Letter
                            </Button>
                            <Menu
                                                                        id="basic-menu"
                                                                        anchorEl={anchorEl}
                                                                        open={open}
                                                                        onClose={handleClose}
                                                                        MenuListProps={{
                                                                        'aria-labelledby': 'basic-button',
                                                                        }}
                                                                    >
                                                                        <MenuItem onClick={handleClose}>Profile</MenuItem>
                                                                        <MenuItem onClick={handleClose}>My account</MenuItem>
                                                                        <MenuItem onClick={handleClose}>Logout</MenuItem>
                            </Menu>
                    </div>

                    <div>
                            <Button
                                                                        id="basic-button"
                                                                        aria-controls={open ? 'basic-menu' : undefined}
                                                                        aria-haspopup="true"
                                                                        aria-expanded={open ? 'true' : undefined}
                                                                        onClick={handleClick}
                                                                    >
                                                                        Tailor Cover Letter
                            </Button>
                            <Menu
                                                                        id="basic-menu"
                                                                        anchorEl={anchorEl}
                                                                        open={open}
                                                                        onClose={handleClose}
                                                                        MenuListProps={{
                                                                        'aria-labelledby': 'basic-button',
                                                                        }}
                                                                    >
                                                                        <MenuItem onClick={handleClose}>Profile</MenuItem>
                                                                        <MenuItem onClick={handleClose}>My account</MenuItem>
                                                                        <MenuItem onClick={handleClose}>Logout</MenuItem>
                            </Menu>
                    </div>
 </div>
            </div>
        </div>
        <div className="options">
            <span className="cancel" onClick={() => {
                jobTitleInputRef.current.value = job.jobTitle;
                companyInputRef.current.value = job.company;
                jobTypeInputRef.current.value = job.jobType;
                locationInputRef.current.value = job.location;
                dateAppliedInputRef.current.value = job.dateApplied;
                durationInputRef.current.value = job.duration;
                linkInputRef.current.value = job.link;
                coverLetterInputRef.current.value = job.coverLetter;
                tailoredCoverLetterInputRef.current.value = job.tailoredCoverLetter;
                setTempTags([...tags])
            }}>Cancel</span>
            <span className="update" onClick={() => {
                console.log('dispatching update job async');
                dispatch(updateJobAsync({id: job._id, fields: {jobTitle, company, jobType, location, dateApplied, duration, link, coverLetter, tailoredCoverLetter, temptags}}));
                setTags([...temptags])
            }}>Save Changes</span> 
        </div>
        </>
    );
} 

 