import JobList from "./JobList";
import Job from "./Job";
import '../../styles/JobsContainer.css';
import { useState } from 'react';
import Form from './addForm'
/* JobsContainer.jsx and JobsContainer.css was generated by ChatGPT 3.5 on May 5th, 2024
Multiple prompts were used, with the component code being tweaked overtime

prompt 1: "with Job rendered in Joblist, is it still possible to format the components so that when a certain job is clicked in joblist
the job's details (Job) is rendered on the right, similar to this picture?" + picture of LinkedIn jobs dashboard
prompt 2: "how do I change the styling so that the job list panel on the left's width stays constant regardless of which job I click"
prompt 3: "thanks! how do I make it so that both the job-list-container and job-details-container both have a scroll bar on the right even if the content doesn't overflow?"
prompt 4: "how do I make job-item also stay gray when it is selected?" */


export default function JobsContainer({selectedJob, setSelectedJob}) {
    
    const [selectForm, setSelectForm] = useState(false)

    return(
        <div className = "jobs-container">
            <JobList onSelectJob={setSelectedJob} selectForm={selectForm} setSelectForm={setSelectForm} selectedJob={selectedJob}/>
            <div className="job-details-container">
                {selectedJob ? <Job job={selectedJob}/> : selectForm? <Form selectForm={selectForm} setSelectForm={setSelectForm} setSelectedJob={setSelectedJob}/> : <h2>Select a job to see in detail</h2>}
            </div>
        </div>
    )
}