import React, { useState } from "react";
import { Link } from 'react-router-dom';
import '../../styles/Navbar.css'
import SearchIcon from '@mui/icons-material/Search';
import { useDispatch, useSelector } from "react-redux";
import { searchJobsAsync } from "../../redux/jobs/thunks";
import InputBase from '@mui/material/InputBase';
import { styled, alpha } from '@mui/material/styles';
import Tooltip, { tooltipClasses } from '@mui/material/Tooltip';
import PostAddIcon from '@mui/icons-material/PostAdd';
import ManageAccountsIcon from '@mui/icons-material/ManageAccounts';
import LogoutIcon from '@mui/icons-material/Logout';
import { IconButton } from "@mui/material";
import { useTheme } from "@emotion/react";
import { useNavigate, useLocation } from "react-router-dom";

export default function Navbar(props) {

    const userEmail = useSelector(state => state.userEmail.userEmail);
    const dispatch = useDispatch()
    const navigate = useNavigate()
    const location = useLocation()
    const [filter, setfilter] = useState('')
    const theme = useTheme();

    const SearchIconWrapper = styled('div')(({ theme }) => ({
        padding: theme.spacing(0, 5),
        height: '100%',
        position: 'absolute',
        pointerEvents: 'none',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    }));
    

    const LightTooltip = styled(({ className, ...props }) => (
    <Tooltip {...props} classes={{ popper: className }} />
    ))(({ theme }) => ({
    [`& .${tooltipClasses.tooltip}`]: {
        backgroundColor: '#FFFFFF',
        color: 'rgba(0, 0, 0, 0.87)',
        boxShadow: theme.shadows[1],
        fontSize: 11,
        fontFamily: "Montserrat",
        borderRadius: '30px'
    },
    }));

    const logOut = () => {
        localStorage.removeItem('jwtToken');
        localStorage.removeItem('userEmail');
    }


    // handleEditAccountClick was generated by ChatGPT-4 on Aug 6, 2024
    // The prompt used was: "how would I figure out whether to navigate 
    // to maindashboard or to coverletterpage when the back button is clicked? 
    // so If I'm on the main dashboard, we should be able to navigate to the 
    // maindashboard when back is clicked, but it would navigate to coverletterpage
    // if user is on the coverletterpage"
    // Four subsequent follow-ups were given, as I needed to clarify what
    // I meant and specified that I used React-Router-Dom
    const handleEditAccountClick = () => {
        navigate('/EditAccount', { state: { from: location.pathname } });
    };


    return(
        <nav className={"navBar"}>
            <div className={"navBar-Left"}>
                <h1 color={theme.palette.bg} className=" cursor-pointer" onClick={() => {navigate("/maindashboard")}}>Application Tailor</h1>
                {props.search && <div className={"searchBar-wrapper ml-6"}>
                    <SearchIconWrapper>
                        <SearchIcon className="searchIcon"/>
                    </SearchIconWrapper>
                    <InputBase type={"text"} 
                                className={"searchBar"} 
                                placeholder={"Search jobs"} 
                                value={filter} 
                                sx={{fontFamily: "Montserrat"}}
                                onChange={(e) => {
                                    setfilter(e.target.value)
                                    if (e.target.value == '') {
                                        let filter = e.target.value
                                        dispatch(searchJobsAsync({filter, userEmail}))
                                    }
                                }}
                                onKeyUp={(e) => {
                                    if (e.key === 'Enter') {
                                        props.setSelectedJob(null);

                                        dispatch(searchJobsAsync({filter, userEmail}));
                                    }}}/>
                    
                </div>}
            </div>
            <div className={"navBar-Right"}>
                <div className={"navBar-Buttons"}>
                    <LightTooltip title='Create Cover Letter'>
                        <Link to="/CoverLetterPage">
                            <IconButton>
                                <PostAddIcon fontSize="large" sx={{color: theme.palette.bg}}/>
                            </IconButton>
                        </Link>
                    </LightTooltip>
                    <LightTooltip title='Edit Account'>
                            <IconButton onClick={handleEditAccountClick}>
                                <ManageAccountsIcon fontSize="large" sx={{color: theme.palette.bg}}/>
                            </IconButton>
                    </LightTooltip>
                    <LightTooltip title='Sign Out'>
                        <Link to="/Login">
                            <IconButton className="iconButton" onClick={logOut}>
                                <LogoutIcon className='logoutIcon' fontSize="large" sx={{color: theme.palette.bg}}/>
                            </IconButton>
                        </Link>
                    </LightTooltip>
                </div>
            </div>
        </nav>
    );
}